2024-02-29 17:49:09,037 - INFO - Error getting local ip: timed out from get_local_ip() at line 40 in core/constants.py
